name: mariadboperatordemo
volumes:
  operator-volume:
    driver: local

services:
  dockeroperator:
    build:
      dockerfile: .docker/Dockerfile
    volumes:
      - operator-volume:/terraform/dev
      - ./.kube:/root/.kube
      - ./utils:/operator/examples
    attach: false
    env_file: ".env"
