apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals
# metadata:name must match the persistentVolumeClaim:claimName and the volumeMounts:name photo-prism-pvc.yaml 
spec:
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi