apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism
  # metadata:name must match the persistentVolumeClaim:claimName and the volumeMounts:name photo-prism-pvc.yaml 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi